<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Barang;
use Carbon\Carbon;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // Audio Visual
            [
                'kategori_id' => 1,
                'kode_barang' => 'BRG-PRJ-01',
                'nama_barang' => 'Proyektor HD',
                'merk' => 'Epson',
                'type' => 'EB-X41',
                'seri' => 'X41-2023',
                'tahun_produksi' => 2023,
                'spesifikasi' => 'XGA (1024 x 768) resolution, 3,600 lumens brightness, HDMI, VGA, USB connectivity',
                'warna' => 'Putih',
                'berat' => 2.5,
                'dimensi' => '30x20x10',
                'garansi' => '2 tahun',
                'tanggal_pembelian' => '2023-06-15',
                'harga_beli' => 8500000,
                'deskripsi' => 'Proyektor resolusi tinggi untuk presentasi dan acara multimedia',
                'jumlah_total' => 2,
                'jumlah_tersedia' => 2,
                'kondisi' => 'baik',
                'lokasi' => 'Multimedia Room / Convention Hall',
                'foto' => 'barang/proyektor.png',
                'harga_sewa' => 50000,
                'status' => 'tersedia',
            ],
            [
                'kategori_id' => 1,
                'kode_barang' => 'BRG-SS-01',
                'nama_barang' => 'Speaker & Sound System',
                'merk' => 'JBL',
                'type' => 'EON615',
                'seri' => 'EON-615-PRO',
                'tahun_produksi' => 2022,
                'spesifikasi' => '1000W powered speaker, 15" woofer, Bluetooth connectivity, XLR/TRS inputs',
                'warna' => 'Hitam',
                'berat' => 18.6,
                'dimensi' => '46x38x69',
                'garansi' => '3 tahun',
                'tanggal_pembelian' => '2022-08-20',
                'harga_beli' => 12000000,
                'deskripsi' => 'Sistem suara profesional untuk acara besar dan konser',
                'jumlah_total' => 1,
                'jumlah_tersedia' => 1,
                'kondisi' => 'baik',
                'lokasi' => 'Convention Hall',
                'foto' => 'barang/speaker.png',
                'harga_sewa' => 100000,
                'status' => 'tersedia',
            ],

            // Furniture
            [
                'kategori_id' => 2,
                'kode_barang' => 'BRG-KRS-01',
                'nama_barang' => 'Kursi Lipat',
                'merk' => 'Chitose',
                'type' => 'Folding Chair',
                'seri' => 'FC-100',
                'tahun_produksi' => 2021,
                'spesifikasi' => 'Plastik PP berkualitas tinggi, tahan cuaca, lipat praktis',
                'warna' => 'Biru',
                'berat' => 3.2,
                'dimensi' => '45x45x80',
                'garansi' => '1 tahun',
                'tanggal_pembelian' => '2021-03-10',
                'harga_beli' => 150000,
                'deskripsi' => 'Kursi lipat plastik serbaguna untuk berbagai acara',
                'jumlah_total' => 100,
                'jumlah_tersedia' => 100,
                'kondisi' => 'baik',
                'lokasi' => 'Convention Hall / Aula',
                'foto' => 'barang/kursi lipat.png',
                'harga_sewa' => 5000,
                'status' => 'tersedia',
            ],
            [
                'kategori_id' => 2,
                'kode_barang' => 'BRG-MJG-01',
                'nama_barang' => 'Meja Lipat',
                'merk' => 'Indachi',
                'type' => 'Folding Table',
                'seri' => 'FT-180',
                'tahun_produksi' => 2021,
                'spesifikasi' => 'Top kayu lapis dilapisi HPL, kaki besi powder coating',
                'warna' => 'Coklat Kayu',
                'berat' => 25.5,
                'dimensi' => '180x80x75',
                'garansi' => '2 tahun',
                'tanggal_pembelian' => '2021-04-15',
                'harga_beli' => 750000,
                'deskripsi' => 'Meja lipat besar untuk pelatihan, seminar, dan pameran',
                'jumlah_total' => 20,
                'jumlah_tersedia' => 20,
                'kondisi' => 'baik',
                'lokasi' => 'Ruang Rapat / Showroom',
                'foto' => 'barang/meja lipat.png',
                'harga_sewa' => 10000,
                'status' => 'tersedia',
            ],

            // Komputer & IT
            [
                'kategori_id' => 3,
                'kode_barang' => 'BRG-PC-01',
                'nama_barang' => 'Komputer Desktop',
                'merk' => 'ASUS',
                'type' => 'All-in-One',
                'seri' => 'V241FAK-BA441T',
                'tahun_produksi' => 2022,
                'spesifikasi' => 'Intel Core i3-10110U, 4GB RAM, 1TB HDD, 23.8" Monitor, Windows 11',
                'warna' => 'Hitam',
                'berat' => 5.8,
                'dimensi' => '54x35x18',
                'garansi' => '3 tahun',
                'tanggal_pembelian' => '2022-01-20',
                'harga_beli' => 9500000,
                'deskripsi' => 'Komputer desktop all-in-one untuk lab multimedia dan pembelajaran',
                'jumlah_total' => 30,
                'jumlah_tersedia' => 30,
                'kondisi' => 'baik',
                'lokasi' => 'Lab Multimedia',
                'foto' => 'barang/komputer.png',
                'harga_sewa' => 0,
                'status' => 'tersedia',
            ],
            [
                'kategori_id' => 3,
                'kode_barang' => 'BRG-VR-01',
                'nama_barang' => 'Oculus VR Headset',
                'merk' => 'Meta',
                'type' => 'Quest 2',
                'seri' => 'MH-A3A00',
                'tahun_produksi' => 2023,
                'spesifikasi' => '128GB storage, 6DOF tracking, 90Hz refresh rate, hand tracking',
                'warna' => 'Putih',
                'berat' => 0.503,
                'dimensi' => '19x14x10',
                'garansi' => '1 tahun',
                'tanggal_pembelian' => '2023-09-10',
                'harga_beli' => 5500000,
                'deskripsi' => 'Perangkat VR terbaru untuk pengalaman virtual reality dan augmented reality',
                'jumlah_total' => 5,
                'jumlah_tersedia' => 5,
                'kondisi' => 'baik',
                'lokasi' => 'Oculus VR Room',
                'foto' => 'barang/oculus vr.png',
                'harga_sewa' => 600000,
                'status' => 'tersedia',
            ],

            // Alat Studio
            [
                'kategori_id' => 4,
                'kode_barang' => 'BRG-LG-01',
                'nama_barang' => 'Lampu Studio',
                'merk' => 'Godox',
                'type' => 'SL-60W',
                'seri' => 'SL60W-2023',
                'tahun_produksi' => 2023,
                'spesifikasi' => '60W LED continuous light, 5600K color temperature, CRI 96+, Bowens mount',
                'warna' => 'Hitam',
                'berat' => 1.95,
                'dimensi' => '22x15x20',
                'garansi' => '2 tahun',
                'tanggal_pembelian' => '2023-05-12',
                'harga_beli' => 2800000,
                'deskripsi' => 'Lampu LED profesional untuk studio foto dan video production',
                'jumlah_total' => 5,
                'jumlah_tersedia' => 5,
                'kondisi' => 'baik',
                'lokasi' => 'Studio Foto',
                'foto' => 'barang/lampu studio.png',
                'harga_sewa' => 50000,
                'status' => 'tersedia',
            ],
            [
                'kategori_id' => 4,
                'kode_barang' => 'BRG-MIX-01',
                'nama_barang' => 'Sound Mixer',
                'merk' => 'Yamaha',
                'type' => 'MG10XU',
                'seri' => 'MG10XU-V2',
                'tahun_produksi' => 2022,
                'spesifikasi' => '10-channel mixing console, built-in SPX effects, USB interface, phantom power',
                'warna' => 'Hitam',
                'berat' => 2.4,
                'dimensi' => '32x22x7',
                'garansi' => '3 tahun',
                'tanggal_pembelian' => '2022-11-05',
                'harga_beli' => 4500000,
                'deskripsi' => 'Mixer audio profesional untuk dubbing, recording, dan live performance',
                'jumlah_total' => 1,
                'jumlah_tersedia' => 1,
                'kondisi' => 'baik',
                'lokasi' => 'Studio Dubbing',
                'foto' => 'barang/sound mixer.png',
                'harga_sewa' => 75000,
                'status' => 'tersedia',
            ],
            [
                'kategori_id' => 4,
                'kode_barang' => 'BRG-KMR-01',
                'nama_barang' => 'Kamera Profesional',
                'merk' => 'Canon',
                'type' => 'EOS R6 Mark II',
                'seri' => 'R6M2-2023',
                'tahun_produksi' => 2023,
                'spesifikasi' => '24.2MP full-frame sensor, 4K video recording, dual card slots, image stabilization',
                'warna' => 'Hitam',
                'berat' => 0.588,
                'dimensi' => '14x10x9',
                'garansi' => '2 tahun internasional',
                'tanggal_pembelian' => '2023-07-18',
                'harga_beli' => 42000000,
                'deskripsi' => 'Kamera DSLR mirrorless profesional untuk studio foto dan videografi',
                'jumlah_total' => 1,
                'jumlah_tersedia' => 1,
                'kondisi' => 'baik',
                'lokasi' => 'Studio Foto',
                'foto' => 'barang/kamera.png',
                'harga_sewa' => 75000,
                'status' => 'tersedia',
            ],

            // Olahraga & Outdoor
            [
                'kategori_id' => 5,
                'kode_barang' => 'BRG-FIT-01',
                'nama_barang' => 'Alat Fitness Outdoor',
                'merk' => 'TRX',
                'type' => 'Suspension Trainer',
                'seri' => 'TRX-GO-2023',
                'tahun_produksi' => 2023,
                'spesifikasi' => 'Suspension trainer set, resistance bands, door anchor, workout guide',
                'warna' => 'Hitam Kuning',
                'berat' => 1.1,
                'dimensi' => '15x10x8',
                'garansi' => '1 tahun',
                'tanggal_pembelian' => '2023-04-25',
                'harga_beli' => 2200000,
                'deskripsi' => 'Peralatan olahraga outdoor untuk fitness dan training di taman',
                'jumlah_total' => 10,
                'jumlah_tersedia' => 10,
                'kondisi' => 'baik',
                'lokasi' => 'Taman Fitness',
                'foto' => 'barang/alat fitness.png',
                'harga_sewa' => 0,
                'status' => 'tersedia',
            ],
        ];

        foreach ($data as $item) {
            Barang::create($item);
        }
    }
}